### ISSUE TITLE
Verificar json de retorno

### ISSUE THREAD

**Issue by fernandossouza** [marcusbianchi/productionorderservice#5]
Json de retorno está com o productid diferente do id do produto real

 "phases": [
                {
                    "phaseId": 9,
                    "phaseName": "colocar sal",
                    "phaseCode": "1100",
                    "phaseProducts": [
                        {
                            "phaseProductId": 9,
                            "productId": 7,
                            "value": "50",
                            "measurementUnit": "kg",
                            "phaseProductType": "finished",
                            "product": {
                                "productId": 11,
                                "productName": "teririra",
                                "productDescription": "twefrasdkj",
                                "productGTIN": "rweioj"
                            }
                        },

**Comment by marcusbianchi** [comment]
Solved on todays commiut
